---
title: "DEEB Evaluation -- Losses"
date: "`r format(Sys.Date())`"
output: 
  html_document:
    toc: no
    toc_float: no
    toc_depth: 6
    number_sections: no
params:
  paths: 
  - "~/DEEBDB9/lorenz63random/Eval_Const_Task01.csv"
  - "~/DEEBDB9/lotkaVolterra/Eval_Trivial_Task01.csv"
  - "~/DEEBDB9/lotkaVolterra/Eval_Colloc_Task01.csv"
  - "~/DEEBDB9/lotkaVolterra/Eval_Altopi_Task01.csv"
  - "~/DEEBDB9/lotkaVolterra/Eval_Const_Task02.csv"
  - "~/DEEBDB9/lotkaVolterra/Eval_Trivial_Task02.csv"
  - "~/DEEBDB9/lotkaVolterra/Eval_Colloc_Task02.csv"
  - "~/DEEBDB9/lotkaVolterra/Eval_Altopi_Task02.csv"
  reference: "Const"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(tidyverse.quiet = TRUE)
library(tidyverse)
```

```{r, include=FALSE}
esti <-
  params$paths |> 
  map(~ read_csv(.) |> pivot_longer(-c(method, ends_with("Nr")), names_to="loss")) |> 
  reduce(bind_rows)
reference <- 
  esti |> 
  filter(method == .env$params$reference) |> 
  mutate(refValue = ifelse(value == 0, 1, value), value = NULL)
data <- 
  left_join(
    esti, 
    reference |> select(-method), 
    by = c("truthNr", "obsNr", "taskNr", "loss")
  ) |> 
  mutate(value = value / refValue)
```

```{r, include=FALSE}
bkgndCols <- colorRampPalette(c(
  rgb(0.5,1,0.5),
  rgb(1,1,0.5),
  rgb(1,0.5,0.5)))(100)

lossColor <- function(loss) {
  i <- 1 + round(loss*100)
  colors <- bkgndCols[i]
  colors[is.na(colors)] <- rgb(1,0,1)
  colors
}

colorizeTable <- function(k, colorCols, lossTbl) {
  for (i in seq_along(colorCols)) {
    k <- kableExtra::column_spec(
      k, 
      colorCols[i],
      background = lossColor(lossTbl[[i]]))
  }
  k
}
showLossTable <- function(d, caption) {
  nMethods <- length(unique(d$method))
  dWide <- 
    d |> 
    select(method, truthNr, value) |>
    pivot_wider(names_from = method, values_from = value) 
  dWide |> 
    kableExtra::kbl(
      digits = 3,
      caption = caption,
      booktabs = TRUE,
      align = c("l", "l", "l", rep("r", nMethods))
    ) |> 
    kableExtra::kable_styling(
      bootstrap_options = c("striped", "condensed"),
      latex_options = c("striped", "HOLD_position"),
      full_width = FALSE) |> 
    colorizeTable(1 + seq_len(ncol(dWide)-1), dWide[,-1])
}
```


# Losses {.tabset}

```{r results='asis'}
for (tnr in unique(data$taskNr)) {
  cat("## Task", tnr, " {.tabset}\n")
  taskData <- filter(data, taskNr == tnr)
  for (lss in unique(taskData$loss)) {
    cat("### Loss", lss, " {.tabset}\n")
    lssData <- filter(taskData, loss == lss)
    for (onr in unique(lssData$obsNr)) {
      cat("#### ObsNr", onr, "\n")
      obsData <- filter(lssData, obsNr == onr)
      cat(showLossTable(
        obsData,
        paste0("Task ", tnr, ": ", lss, "-Loss (obsNr: ", onr, ")")))
    }
  }
}
```



