---
title: "DEEB Evaluation"
date: "`r format(Sys.Date())`"
output: 
  html_document:
    toc: no
    toc_float: no
    toc_depth: 6
    number_sections: no
params:
  paths: 
  - "~/DEEBDB2/lotkaVolterra/evaluation/task01Const_eval.csv"
  - "~/DEEBDB2/lotkaVolterra/evaluation/task01TrvlPl_eval.csv"
  - "~/DEEBDB2/lotkaVolterra/evaluation/task01Truth_eval.csv"
  - "~/DEEBDB2/lotkaVolterra/evaluation/task02Const_eval.csv"
  - "~/DEEBDB2/lotkaVolterra/evaluation/task02TrvlPl_eval.csv"
  - "~/DEEBDB2/lotkaVolterra/evaluation/task02Truth_eval.csv"
  reference: "Const"
  best: "Truth"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(purrr)
library(readr)
library(stringr)
```

```{r, include=FALSE}
esti <-
  params$paths |> 
  map(~ read_csv(.) |> tidyr::pivot_longer(-c(method, ends_with("Nr")), names_to="loss")) |> 
  reduce(bind_rows)
reference <- 
  esti |> 
  filter(method == .env$params$reference) |> 
  rename(refValue = value) |> 
  select(-method)
best <- 
  esti |> 
  filter(method == .env$params$best) |> 
  rename(bestValue = value) |> 
  select(-method)
data <- 
  esti |> 
  left_join(reference, by = c("truthNr", "obsNr", "taskNr", "loss")) |> 
  left_join(best, by = c("truthNr", "obsNr", "taskNr", "loss")) |> 
  mutate(skillScore = (value - refValue) / (bestValue - refValue)) # skill score
```

```{r, include=FALSE}
nColors <- 256
bkgndCols <- colorRampPalette(c(
  rgb(0.5,1,0.5),
  rgb(1,1,0.5),
  rgb(1,0.5,0.5)))(nColors)

lossColor <- function(score) {
  score <- pmin(1, score)
  i <- 1 + floor((1-score)*nColors)
  colors <- bkgndCols[i]
  colors[score <= 0] <- rgb(1,0.5,1)
  colors[is.na(colors)] <- rgb(0.6,0.6,0.6)
  colors
}

colorizeTable <- function(k, colorCols, lossTbl) {
  for (i in seq_along(colorCols)) {
    k <- kableExtra::column_spec(
      k, 
      colorCols[i],
      background = lossColor(lossTbl[[colorCols[i]]]))
  }
  k
}
showSkillScoreTable <- function(d, caption, digits=3, format = "f") {
  if (nrow(d) == 0) return(paste0(caption, ": no data"))
  nMethods <- length(unique(d$method))
  dText <- 
    d |> 
    mutate(text = sprintf(paste0("%.",digits, format," (%d)"), value, rank)) 
  dWideSkill <- 
    d |> 
    mutate(value = ifelse(skillScore < 0, 0, skillScore)) |> 
    select(method, truthNr, value) |>
    tidyr::pivot_wider(names_from = method, values_from = value) 
  dTextWide <- 
    dText |> 
    select(method, truthNr, text) |>
    tidyr::pivot_wider(names_from = method, values_from = text) 
  dTextWide |> 
    kableExtra::kbl(
      caption = caption,
      booktabs = TRUE,
      align = c("l", "l", "l", rep("r", nMethods))
    ) |> 
    kableExtra::kable_styling(
      bootstrap_options = c("condensed"),
      latex_options = c("HOLD_position"),
      full_width = FALSE) |> 
    colorizeTable(1 + seq_len(ncol(dWideSkill)-1), dWideSkill)
}

# T-statistic confidence interval
tConfInt <- function(x, level, side = c("left", "right")) {
  side <- match.arg(side)
  x <- x[!is.na(x)]
  n <- length(x)
  if (n == 0) return(NA)
  switch(
    side,
    left = mean(x) - sd(x)*qt(1-(1-level)/2, n-1) / sqrt(n),
    right = mean(x) + sd(x)*qt(1-(1-level)/2, n-1) / sqrt(n))
}

showStatsTable <- function(d, caption, digits=3, format = "f", colorize="zeroOne") {
  if (nrow(d) == 0) return(paste0(caption, ": no data"))
  dStats <- 
    d |> 
    group_by(method) |> 
    summarize(
      mean = mean(value, na.rm = TRUE),
      sd = sd(value, na.rm = TRUE),
      ci95l = tConfInt(value, level = 0.95, side = "left"),
      ci95r = tConfInt(value, level = 0.95, side = "right"),
      min = min(value, na.rm = TRUE),
      q25 = quantile(value, probs = 0.25, na.rm = TRUE),
      median = median(value, na.rm = TRUE),
      q75 = quantile(value, probs = 0.75, na.rm = TRUE),
      max = max(value, na.rm = TRUE),
      n = sum(!is.na(value)),
      "NA" = sum(is.na(value))
    ) |> 
    arrange(desc(mean))
  numberCols <- ncol(dStats) - 3 # not first and not last 2 (n, NA)
  dText <- dStats
  for (i in 1+seq_len(numberCols)) {
    dText[[i]] <- sprintf(paste0("%.",digits, format), dText[[i]])
  }
  tbl <- 
    dText |> 
    kableExtra::kbl(
      caption = caption,
      booktabs = TRUE,
      align = c("l", rep("r", ncol(dStats) - 1))
    ) |> 
    kableExtra::kable_styling(
      bootstrap_options = c("condensed"),
      latex_options = c("HOLD_position"),
      full_width = FALSE) 
  tbl <- switch(
    colorize,
    none = tbl,
    zeroOne = colorizeTable(tbl, setdiff(1+seq_len(numberCols), 3), dStats),
    stop("unknown colorize value"))
  return(tbl)
}
```


```{r results='asis'}
pth <- normalizePath(params$paths[1], winslash="/")
fldrs <- str_split(path, "/")[[1]]
i <- which(fldrs == "evaluation")
if (length(i) == 1) {
  cat("\n\n**")
  cat(fldrs[seq_len(i-1)], sep="/")
  cat("**\n\n")
}
```

[Plots](./showPlots.html)

```{r results='asis'}
if ("example" %in% fldrs) {
  cat("[Navi](../../../navi.html)\n")
} else {
  cat("[Navi](../../navi.html)\n")
}
```

# Skill Scores {.tabset}

```{r}
showObsSkillScoreTables <- function(obsData, title, showAll) {
  obsData <- 
    obsData |> 
    mutate(value = skillScore) |> # show skill scores only; not absolute values
    group_by(truthNr, obsNr, taskNr) |> 
    filter(!all(is.na(value))) |> 
    mutate(value = ifelse(abs(value) <= .Machine$double.eps, 0, value)) |> # make sure that -0 is 0
    mutate(rank = rank(-pmax(0, value), ties.method = "max", na.last = "keep")) |> 
    mutate(rankScore = 1 - (rank - min(rank, na.rm=TRUE)) / (max(rank, na.rm=TRUE) - min(rank, na.rm=TRUE))) |> 
    ungroup()
  
  rankScoreData <- 
    obsData |> 
    mutate(value = rankScore)
  
  meanScoreData <- 
    obsData |> 
    mutate(value = ifelse(value < 0, 0, value))
  
  cat("\n\n")
  cat(showStatsTable(
    meanScoreData,
    paste0(title, " - Trimmed Score Statistics")))
  
  cat("\n\n")
  cat(showStatsTable(
    rankScoreData,
    paste0(title, " - Rank Score Statistics")))
  
  if (showAll) {
    cat("\n\n")
    cat(showSkillScoreTable(
      obsData,
      paste0(title, " - Skill Scores (Rank)")))
  }
  
  cat("\n\n")
}
```

```{r results='asis'}
for (tnr in unique(data$taskNr)) {
  cat("## Task", tnr, " {.tabset}\n")
  taskData <- filter(data, taskNr == tnr)
  for (lss in unique(taskData$loss)) {
    cat("### Score", lss, " {.tabset}\n")
    lssData <- filter(taskData, loss == lss)
    cat("#### ObsNr all\n\n")
    showObsSkillScoreTables(
      lssData, 
      paste0("Task ", tnr, ", all obs: ", lss),
      showAll = FALSE)
    for (onr in unique(lssData$obsNr)) {
      cat("#### ObsNr", onr, "\n\n")
      obsData <- filter(lssData, obsNr == onr)
      showObsSkillScoreTables(
        obsData, 
        paste0("Task ", tnr, ", obsNr ", onr, ": ", lss),
        showAll = TRUE)
    }
  }
}
```


# Absolute Scores {.tabset}


```{r}
showObsAbsScoreTables <- function(obsData, title, showAll) {
  obsData <- 
    obsData |> 
    group_by(truthNr, obsNr, taskNr) |> 
    filter(!all(is.na(value))) |> 
    mutate(rank = rank(value, ties.method = "max", na.last = "keep")) |> 
    ungroup()
  
  cat("\n\n")
  cat(showStatsTable(
    obsData,
    paste0(title, " - Score Statistics"),
    colorize = "none", format = "g"))
   
  if (showAll) {
    cat("\n\n")
    cat(showSkillScoreTable(
      obsData,
      paste0(title, " - Scores (Rank)"), 
      format = "g"))
  }
  
  cat("\n\n")
}
```

```{r results='asis'}
for (tnr in unique(data$taskNr)) {
  cat("## Task", tnr, " {.tabset}\n")
  taskData <- filter(data, taskNr == tnr)
  for (lss in unique(taskData$loss)) {
    cat("### Score", lss, " {.tabset}\n")
    lssData <- filter(taskData, loss == lss)
    cat("#### ObsNr all\n\n")
    showObsAbsScoreTables(
      lssData, 
      paste0("Task ", tnr, ", all obs: ", lss),
      showAll = FALSE)
    for (onr in unique(lssData$obsNr)) {
      cat("#### ObsNr", onr, "\n\n")
      obsData <- filter(lssData, obsNr == onr)
      showObsAbsScoreTables(
        obsData, 
        paste0("Task ", tnr, ", obsNr ", onr, ": ", lss),
        showAll = TRUE)
    }
  }
}
```



